# Site settings
title: Brendan Code's
header-img: img/home-bg.png
email: brendan.dwyer@live.com
copyright_name: bdwyz
description: > # this means to ignore newlines until "baseurl:"
  I'm Brendan and this is my coding journey.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: bdwyz
github_username:  bdwyz
learn_profile: bdwyz
email_username: brendan.dwyer@live.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
